name: Volter_Shop
version: 1.1.0
main: dev.shop.VolterShop
api-version: '1.20'
softdepend: [Vault, PlayerPoints, PlaceholderAPI]
commands:
  shop:
    description: Open the shop
    aliases: [store]
    usage: /shop [reload]
permissions:
  shop.use:
    default: true
  shop.reload:
    default: op
